version: "3"
services:
  api:
    build: ./api
    depends_on:
      - postgres
    networks:
      - local
    environment:
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_NAME: ${DATABASE_NAME}
      NODE_ENV: development
      PORT: 5000
    ports:
      - "5000:5000"
  postgres:
    image: postgres:10.4
    networks:
      - local
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
  frontend:
      build: ./dashboard
      ports:
          - "3000:3000"
networks:
  local:
