version: "3"
services:
  api:
    build: ./api
    depends_on:
      - postgres
    networks:
      - local
    environment:
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: admin
      DATABASE_HOST: postgres
      NODE_ENV: development
      PORT: 5000
    ports:
      - "5000:5000"
  postgres:
    image: postgres:10.4
    networks:
      - local
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: guard_rails
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  migration:
    build: ./api
    command: bash -c "sequelize db:create && sequelize db:migrate"
  frontend:
      build: ./dashboard
      ports:
          - "3000:3000"
      volumes:
          - ./client:/usr/src/app
networks:
  local:
